# Generated by Django 5.0.3 on 2024-04-19 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('cod_pro', models.AutoField(primary_key=True, serialize=False)),
                ('nom_pro', models.CharField(max_length=50)),
                ('desc', models.TextField(blank=True, null=True)),
                ('stock', models.IntegerField()),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nom_usr', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('ape', models.CharField(max_length=50)),
                ('dni', models.IntegerField()),
                ('tel', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('cod_compra', models.AutoField(primary_key=True, serialize=False)),
                ('cant', models.IntegerField()),
                ('monto', models.FloatField()),
                ('cod_pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.producto')),
                ('nom_usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.usuario')),
            ],
        ),
    ]
