# Generated by Django 5.0.3 on 2024-04-19 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='monto',
        ),
    ]
